apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  targetNamespace: podinfo
  releaseName: podinfo
  interval: 10m
  chart:
    spec:
      chart: ./podinfo
      sourceRef:
        kind: GitRepository
        name: podinfo
  values:
    replicaCount: 3
    image:
      repository: ghcr.io/stefanprodan/podinfo
      tag: "6.9.4"
      pullPolicy: IfNotPresent